language: generic

# Use Mac OSX for bash support
os: osx

# Run only on master branch
branches:
  only:
  - master

# Notify on failure
notifications:
  email:
    on_success: never
    on_failure: change

# Make scripts executable
before_install:
- chmod +x ./ScriptsCI/install.sh
- chmod +x ./ScriptsCI/build.sh
- chmod +x ./ScriptsCI/after_build.sh

# Install Unity
install:
- ./ScriptsCI/install.sh

# Run tests and build
script:
- sudo -E ./ScriptsCI/build.sh

# Create release for build
after_success:
- sudo -E ./ScriptsCI/after_build.sh

# Env vars
env:
  global:
  - PROJECT_NAME="Proyecto-Guardabarranca"
  - UNITY_TORRENT_URL="https://download.unity3d.com/download_unity/ca4d5af0be6f/Unity-2019.2.1f1.torrent"
  