language: generic

# Use Mac OSX for bash support
os: osx

# Run only on master branch
branches:
  only:
  - master

# Notify on failure
notifications:
  email:
    on_success: never
    on_failure: change

# Install Unity
install:
- sudo -E ./ScriptsCI/install.sh

# Run tests and build
script:
- sudo -E ./ScriptsCI/build.sh

# Create release for build
after_success:
- sudo -E ./ScriptsCI/after_build.sh

# Env vars
env:
  global:
  - PROJECT_NAME="Proyecto-Guardabarranca"